#!/bin/bash
#SBATCH --job-name=train_model
#SBATCH --output=logs/model.out
#SBATCH --error=logs/model.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=63493M
#SBATCH --time=14-00:00:00
#SBATCH --partition=earth

set -euo pipefail
mkdir -p logs
mkdir -p models

export PYTHONUNBUFFERED=1
export AMBI_NOPROGRESS=1

cd /mnt/Jupiter/project/personal/libambi

ambi-train /mnt/Jupiter/dataset/ambi/clic2024_split/train \
  --config ambi/config_lowrate.yaml \
  --out models/ambi_policy_lowrate.ts \
  --iters 300 \
  --steps 16384 \
  --lr 1e-4 \
  --device cpu

# ambi-train /mnt/Jupiter/dataset/ambi/clic2024_split/train \
#   --config ambi/config_balanced.yaml \
#   --out models/ambi_policy_balanced.ts \
#   --iters 300 \
#   --steps 16384 \
#   --lr 1e-4 \
#   --device cpu

# ambi-train /mnt/Jupiter/dataset/ambi/clic2024_split/train \
#   --config ambi/config_highpsnr.yaml \
#   --out models/ambi_policy_highpsnr.ts \
#   --iters 300 \
#   --steps 16384 \
#   --lr 1e-4 \
#   --device cpu