rl:
  control_split: true

  weights:
    bpp_q1: 0.5
    bpp_med: 1.0
    bpp_q3: 1.5
    psnr_q1: 1.5
    psnr_med: 2.0
    psnr_q3: 0.5
    alpha_bpp: 2.0
    alpha_psnr: 2.0
    alpha_msssim: 1.0
    alpha_mismatch: 0.5

  adapt:
    enabled: true
    boundary_pts: [[0.40, 35.0], [0.30, 32.0]]
    use_stats: { bpp: q3, psnr: q1 }
    ema_beta: 0.9
    gains: { kb: 0.2, kp: 0.2 }
    scales: { bpp: 0.15, psnr: 2.5 }
    trust_region: 0.15
    alpha_bounds: { min: 0.2, max: 10.0 }
    decay_when_ok: 0.01
    warmup_batches: 16
    mode: residuals

  split_bit_cost: 1.0

  loading:
    mode: lazy
    lazy_by: memory
    mem_fraction: 0.8
    batch_size: 32
    iters_per_batch: 1
    aug_per_image: 3
    aug_kinds: [hflip, vflip, rot90]
    shuffle_seed: 0

  msssim_on: "y"
  ds_factor: 1.0
  msssim_pow: 2.0

  early_stop:
    enabled: true
    patience: 15
    min_delta_bpp: 0.005
    min_delta_db: 0.02
    start_after: 20
