# lowrate 

device: cpu

encoder:
  compression: {type: zlib, level: 9}
  min_block: 32
  max_block: 128
  block_size: 16
  default_q: 12
  default_K: 6
  default_H: 8
  num_workers: 8
  chunk_size: 512
  split: {var_thresh: 0.0025, grad_thresh: 0.020}
  refine: {enabled: true, q: 0.02, grid: 4, max_mag: 4}

policy:
  target_bpp: 0.40

prior: {type: deterministic, K: 6}
format: {magic: AMBI, version: 3}

rl:
  control_split: true
  progress_pct: 2

  weights:
    alpha_bpp: 1.8
    alpha_psnr: 1.0
    alpha_msssim: 0.2
    alpha_mismatch: 0.0
    bpp_q1: 0.25
    bpp_med: 0.50
    bpp_q3: 1.00
    psnr_q1: 0.8
    psnr_med: 1.2
    psnr_q3: 0.4

  msssim_floor: 0.95
  min_psnr_db: null
  psnr_margin_db: 0.3
  min_msssim: null
  msssim_on: "y"
  ds_factor: 1.0
  msssim_pow: 1.0

  split_bit_cost: 1.0

  loading:
    mode: lazy
    lazy_by: memory
    mem_fraction: 0.80
    batch_size: 32
    iters_per_batch: 1
    aug_per_image: 3
    aug_kinds: [hflip, vflip, rot90]
    shuffle_seed: 0
    keep_cache: false

  early_stop:
    enabled: true
    patience: 15
    min_delta_bpp: 0.005
    min_delta_db: 0.02
    start_after: 10
